source 'git@github.com:Mackarous/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!
target 'BuildKit_Tests' do
  pod 'RxBuildKit', :path => '../'
  
  pod 'Quick'
  pod 'Nimble'
end
