source 'git@github.com:mackarous/specs.git'
source 'https://github.com/cocoapods/specs.git'

platform :ios, '11.0'

use_frameworks!
target 'BuildKit_Tests' do
  pod 'BuildKit', :path => '../'
  pod 'RxBuildKit', :path => '../'
  
  pod 'Quick'
  pod 'Nimble'
end
